"""Expanded baseball school list: 600+ programs across all NCAA divisions + NAIA/JUCO.

Strategy:
- Schools, conferences, divisions: hand-compiled from public sources (reliable)
- Email domain: school's actual domain
- Email format: "baseball@{domain}" for the program inbox
- Head coach names: ONLY filled in where I have high confidence (top D1 verified earlier).
  Everything else stays blank — the lazy-verify endpoint fills it in when an
  athlete clicks. This is intentional: no fake names ever ship.
- MX verification happens in verify_mx.py after this generates the raw list
"""
import json
from pathlib import Path

# Format: (school, division, conference, domain, tier, head_coach_or_None, inbox_local_or_None)
# tier: reach / match / safety (for a typical recruit; rough guide)
# inbox_local defaults to "baseball" if None
# head_coach: only set for schools verified earlier; None otherwise
SCHOOLS = [
    # =========================================================================
    # NCAA DIVISION I
    # =========================================================================

    # --- SEC (16) ---
    ("Alabama", "D1", "SEC", "ua.edu", "reach", "Rob Vaughn", None),
    ("Arkansas", "D1", "SEC", "uark.edu", "reach", "Dave Van Horn", None),
    ("Auburn", "D1", "SEC", "auburn.edu", "reach", "Butch Thompson", None),
    ("Florida", "D1", "SEC", "gators.ufl.edu", "reach", "Kevin O'Sullivan", None),
    ("Georgia", "D1", "SEC", "uga.edu", "reach", None, None),
    ("Kentucky", "D1", "SEC", "uky.edu", "reach", "Nick Mingione", None),
    ("LSU", "D1", "SEC", "lsu.edu", "reach", "Jay Johnson", None),
    ("Mississippi State", "D1", "SEC", "msstate.edu", "reach", "Brian O'Connor", None),
    ("Missouri", "D1", "SEC", "missouri.edu", "reach", None, None),
    ("Ole Miss", "D1", "SEC", "olemiss.edu", "reach", "Mike Bianco", None),
    ("Oklahoma", "D1", "SEC", "ou.edu", "reach", None, None),
    ("South Carolina", "D1", "SEC", "mailbox.sc.edu", "reach", "Monte Lee", None),
    ("Tennessee", "D1", "SEC", "utk.edu", "reach", "Josh Elander", None),
    ("Texas", "D1", "SEC", "athletics.utexas.edu", "reach", "Jim Schlossnagle", None),
    ("Texas A&M", "D1", "SEC", "athletics.tamu.edu", "reach", "Michael Earley", None),
    ("Vanderbilt", "D1", "SEC", "vanderbilt.edu", "reach", None, None),

    # --- ACC (16) ---
    ("Boston College", "D1", "ACC", "bc.edu", "match", None, None),
    ("California", "D1", "ACC", "berkeley.edu", "match", None, None),
    ("Clemson", "D1", "ACC", "clemson.edu", "reach", None, None),
    ("Duke", "D1", "ACC", "duke.edu", "reach", "Corey Muscara", None),
    ("Florida State", "D1", "ACC", "fsu.edu", "reach", None, None),
    ("Georgia Tech", "D1", "ACC", "gatech.edu", "reach", None, None),
    ("Louisville", "D1", "ACC", "louisville.edu", "reach", None, None),
    ("Miami", "D1", "ACC", "miami.edu", "reach", None, None),
    ("North Carolina", "D1", "ACC", "unc.edu", "reach", None, None),
    ("NC State", "D1", "ACC", "ncsu.edu", "reach", None, None),
    ("Notre Dame", "D1", "ACC", "nd.edu", "reach", None, None),
    ("Pittsburgh", "D1", "ACC", "pitt.edu", "match", None, None),
    ("SMU", "D1", "ACC", "smu.edu", "match", None, None),
    ("Stanford", "D1", "ACC", "stanford.edu", "reach", None, None),
    ("Virginia", "D1", "ACC", "virginia.edu", "reach", "Chris Pollard", None),
    ("Virginia Tech", "D1", "ACC", "vt.edu", "reach", "John Szefc", None),
    ("Wake Forest", "D1", "ACC", "wfu.edu", "reach", None, None),

    # --- Big 12 (16) ---
    ("Arizona", "D1", "Big 12", "arizona.edu", "reach", None, None),
    ("Arizona State", "D1", "Big 12", "asu.edu", "reach", None, None),
    ("Baylor", "D1", "Big 12", "baylor.edu", "match", None, None),
    ("BYU", "D1", "Big 12", "byu.edu", "match", None, None),
    ("Cincinnati", "D1", "Big 12", "uc.edu", "match", None, None),
    ("Houston", "D1", "Big 12", "uh.edu", "match", None, None),
    ("Kansas", "D1", "Big 12", "ku.edu", "match", None, None),
    ("Kansas State", "D1", "Big 12", "ksu.edu", "match", None, None),
    ("Oklahoma State", "D1", "Big 12", "okstate.edu", "reach", None, None),
    ("TCU", "D1", "Big 12", "tcu.edu", "reach", None, None),
    ("Texas Tech", "D1", "Big 12", "ttu.edu", "reach", None, None),
    ("UCF", "D1", "Big 12", "ucf.edu", "match", None, None),
    ("Utah", "D1", "Big 12", "utah.edu", "match", None, None),
    ("West Virginia", "D1", "Big 12", "mail.wvu.edu", "match", "Steve Sabins", None),

    # --- Big Ten (16) ---
    ("Illinois", "D1", "Big Ten", "illinois.edu", "match", None, None),
    ("Indiana", "D1", "Big Ten", "indiana.edu", "match", None, None),
    ("Iowa", "D1", "Big Ten", "uiowa.edu", "match", None, None),
    ("Maryland", "D1", "Big Ten", "umd.edu", "match", None, None),
    ("Michigan", "D1", "Big Ten", "umich.edu", "match", None, None),
    ("Michigan State", "D1", "Big Ten", "msu.edu", "match", None, None),
    ("Minnesota", "D1", "Big Ten", "umn.edu", "match", None, None),
    ("Nebraska", "D1", "Big Ten", "unl.edu", "match", None, None),
    ("Northwestern", "D1", "Big Ten", "northwestern.edu", "match", None, None),
    ("Ohio State", "D1", "Big Ten", "osu.edu", "match", None, None),
    ("Oregon", "D1", "Big Ten", "uoregon.edu", "reach", None, None),
    ("Penn State", "D1", "Big Ten", "psu.edu", "match", None, None),
    ("Purdue", "D1", "Big Ten", "purdue.edu", "match", None, None),
    ("Rutgers", "D1", "Big Ten", "rutgers.edu", "match", None, None),
    ("UCLA", "D1", "Big Ten", "ucla.edu", "reach", None, None),
    ("USC", "D1", "Big Ten", "usc.edu", "reach", None, None),
    ("Washington", "D1", "Big Ten", "uw.edu", "match", None, None),

    # --- AAC (11) ---
    ("Charlotte", "D1", "AAC", "charlotte.edu", "safety", None, None),
    ("East Carolina", "D1", "AAC", "ecu.edu", "match", None, None),
    ("Florida Atlantic", "D1", "AAC", "fau.edu", "safety", None, None),
    ("Memphis", "D1", "AAC", "memphis.edu", "safety", None, None),
    ("North Texas", "D1", "AAC", "unt.edu", "safety", None, None),
    ("Rice", "D1", "AAC", "rice.edu", "match", None, None),
    ("South Florida", "D1", "AAC", "usf.edu", "match", None, None),
    ("Tulane", "D1", "AAC", "tulane.edu", "match", None, None),
    ("UAB", "D1", "AAC", "uab.edu", "safety", None, None),
    ("UTSA", "D1", "AAC", "utsa.edu", "safety", None, None),
    ("Wichita State", "D1", "AAC", "wichita.edu", "match", None, None),

    # --- Sun Belt (14) ---
    ("App State", "D1", "Sun Belt", "appstate.edu", "safety", None, None),
    ("Arkansas State", "D1", "Sun Belt", "astate.edu", "safety", None, None),
    ("Coastal Carolina", "D1", "Sun Belt", "coastal.edu", "match", None, None),
    ("Georgia Southern", "D1", "Sun Belt", "georgiasouthern.edu", "safety", None, None),
    ("Georgia State", "D1", "Sun Belt", "gsu.edu", "safety", None, None),
    ("James Madison", "D1", "Sun Belt", "jmu.edu", "safety", None, None),
    ("Louisiana", "D1", "Sun Belt", "louisiana.edu", "match", None, None),
    ("ULM", "D1", "Sun Belt", "ulm.edu", "safety", None, None),
    ("Marshall", "D1", "Sun Belt", "marshall.edu", "safety", None, None),
    ("Old Dominion", "D1", "Sun Belt", "odu.edu", "safety", None, None),
    ("South Alabama", "D1", "Sun Belt", "southalabama.edu", "safety", None, None),
    ("Southern Miss", "D1", "Sun Belt", "usm.edu", "match", None, None),
    ("Texas State", "D1", "Sun Belt", "txstate.edu", "safety", None, None),
    ("Troy", "D1", "Sun Belt", "troy.edu", "safety", None, None),

    # --- Conference USA (10) ---
    ("Dallas Baptist", "D1", "CUSA", "dbu.edu", "match", None, None),
    ("FIU", "D1", "CUSA", "fiu.edu", "safety", None, None),
    ("Jacksonville State", "D1", "CUSA", "jsu.edu", "safety", None, None),
    ("Kennesaw State", "D1", "CUSA", "kennesaw.edu", "safety", None, None),
    ("Liberty", "D1", "CUSA", "liberty.edu", "safety", None, None),
    ("Louisiana Tech", "D1", "CUSA", "latech.edu", "safety", None, None),
    ("Middle Tennessee", "D1", "CUSA", "mtsu.edu", "safety", None, None),
    ("New Mexico State", "D1", "CUSA", "nmsu.edu", "safety", None, None),
    ("Sam Houston", "D1", "CUSA", "shsu.edu", "safety", None, None),
    ("Western Kentucky", "D1", "CUSA", "wku.edu", "safety", None, None),

    # --- Missouri Valley (10) ---
    ("Belmont", "D1", "MVC", "belmont.edu", "safety", None, None),
    ("Bradley", "D1", "MVC", "bradley.edu", "safety", None, None),
    ("Evansville", "D1", "MVC", "evansville.edu", "safety", None, None),
    ("Illinois State", "D1", "MVC", "illinoisstate.edu", "safety", None, None),
    ("Indiana State", "D1", "MVC", "indstate.edu", "match", None, None),
    ("Missouri State", "D1", "MVC", "missouristate.edu", "safety", None, None),
    ("Murray State", "D1", "MVC", "murraystate.edu", "safety", None, None),
    ("Southern Illinois", "D1", "MVC", "siu.edu", "safety", None, None),
    ("UIC", "D1", "MVC", "uic.edu", "safety", None, None),
    ("Valparaiso", "D1", "MVC", "valpo.edu", "safety", None, None),

    # --- Big West (10) ---
    ("Cal Poly", "D1", "Big West", "calpoly.edu", "safety", None, None),
    ("Cal State Bakersfield", "D1", "Big West", "csub.edu", "safety", None, None),
    ("Cal State Fullerton", "D1", "Big West", "fullerton.edu", "match", None, None),
    ("Cal State Northridge", "D1", "Big West", "csun.edu", "safety", None, None),
    ("Hawaii", "D1", "Big West", "hawaii.edu", "safety", None, None),
    ("Long Beach State", "D1", "Big West", "csulb.edu", "match", None, None),
    ("UC Davis", "D1", "Big West", "ucdavis.edu", "safety", None, None),
    ("UC Irvine", "D1", "Big West", "uci.edu", "match", None, None),
    ("UC Riverside", "D1", "Big West", "ucr.edu", "safety", None, None),
    ("UC San Diego", "D1", "Big West", "ucsd.edu", "safety", None, None),
    ("UC Santa Barbara", "D1", "Big West", "ucsb.edu", "match", None, None),

    # --- Big East (8 baseball) ---
    ("Butler", "D1", "Big East", "butler.edu", "safety", None, None),
    ("Connecticut", "D1", "Big East", "uconn.edu", "match", None, None),
    ("Creighton", "D1", "Big East", "creighton.edu", "safety", None, None),
    ("Georgetown", "D1", "Big East", "georgetown.edu", "safety", None, None),
    ("Seton Hall", "D1", "Big East", "shu.edu", "safety", None, None),
    ("St. John's", "D1", "Big East", "stjohns.edu", "safety", None, None),
    ("Villanova", "D1", "Big East", "villanova.edu", "safety", None, None),
    ("Xavier", "D1", "Big East", "xavier.edu", "safety", None, None),

    # --- Mountain West (10) ---
    ("Air Force", "D1", "MW", "usafa.edu", "safety", None, None),
    ("Fresno State", "D1", "MW", "csufresno.edu", "safety", None, None),
    ("Nevada", "D1", "MW", "unr.edu", "safety", None, None),
    ("New Mexico", "D1", "MW", "unm.edu", "safety", None, None),
    ("San Diego State", "D1", "MW", "sdsu.edu", "safety", None, None),
    ("San Jose State", "D1", "MW", "sjsu.edu", "safety", None, None),
    ("UNLV", "D1", "MW", "unlv.edu", "safety", None, None),
    ("Utah Tech", "D1", "MW", "utahtech.edu", "safety", None, None),

    # --- Pac-12 (remaining) ---
    ("Oregon State", "D1", "Pac-12", "oregonstate.edu", "reach", None, None),
    ("Washington State", "D1", "Pac-12", "wsu.edu", "safety", None, None),

    # --- CAA (11) ---
    ("Campbell", "D1", "CAA", "campbell.edu", "safety", None, None),
    ("Charleston", "D1", "CAA", "cofc.edu", "safety", None, None),
    ("Delaware", "D1", "CAA", "udel.edu", "safety", None, None),
    ("Elon", "D1", "CAA", "elon.edu", "safety", None, None),
    ("Hofstra", "D1", "CAA", "hofstra.edu", "safety", None, None),
    ("Monmouth", "D1", "CAA", "monmouth.edu", "safety", None, None),
    ("North Carolina A&T", "D1", "CAA", "ncat.edu", "safety", None, None),
    ("Northeastern", "D1", "CAA", "northeastern.edu", "safety", None, None),
    ("Stony Brook", "D1", "CAA", "stonybrook.edu", "safety", None, None),
    ("Towson", "D1", "CAA", "towson.edu", "safety", None, None),
    ("UNC Wilmington", "D1", "CAA", "uncw.edu", "safety", None, None),
    ("William & Mary", "D1", "CAA", "wm.edu", "safety", None, None),

    # --- Atlantic 10 (12 baseball) ---
    ("Davidson", "D1", "A-10", "davidson.edu", "safety", None, None),
    ("Dayton", "D1", "A-10", "udayton.edu", "safety", None, None),
    ("Fordham", "D1", "A-10", "fordham.edu", "safety", None, None),
    ("George Mason", "D1", "A-10", "gmu.edu", "safety", None, None),
    ("George Washington", "D1", "A-10", "gwu.edu", "safety", None, None),
    ("La Salle", "D1", "A-10", "lasalle.edu", "safety", None, None),
    ("UMass", "D1", "A-10", "umass.edu", "safety", None, None),
    ("Rhode Island", "D1", "A-10", "uri.edu", "safety", None, None),
    ("Richmond", "D1", "A-10", "richmond.edu", "safety", None, None),
    ("Saint Joseph's", "D1", "A-10", "sju.edu", "safety", None, None),
    ("Saint Louis", "D1", "A-10", "slu.edu", "safety", None, None),
    ("VCU", "D1", "A-10", "vcu.edu", "safety", None, None),

    # --- Big South (8) ---
    ("Charleston Southern", "D1", "Big South", "csuniv.edu", "safety", None, None),
    ("Gardner-Webb", "D1", "Big South", "gardner-webb.edu", "safety", None, None),
    ("High Point", "D1", "Big South", "highpoint.edu", "safety", None, None),
    ("Longwood", "D1", "Big South", "longwood.edu", "safety", None, None),
    ("Presbyterian", "D1", "Big South", "presby.edu", "safety", None, None),
    ("Radford", "D1", "Big South", "radford.edu", "safety", None, None),
    ("UNC Asheville", "D1", "Big South", "unca.edu", "safety", None, None),
    ("Winthrop", "D1", "Big South", "winthrop.edu", "safety", None, None),

    # --- ASUN (11) ---
    ("Austin Peay", "D1", "ASUN", "apsu.edu", "safety", None, None),
    ("Bellarmine", "D1", "ASUN", "bellarmine.edu", "safety", None, None),
    ("Central Arkansas", "D1", "ASUN", "uca.edu", "safety", None, None),
    ("Eastern Kentucky", "D1", "ASUN", "eku.edu", "safety", None, None),
    ("Florida Gulf Coast", "D1", "ASUN", "fgcu.edu", "safety", None, None),
    ("Jacksonville", "D1", "ASUN", "ju.edu", "safety", None, None),
    ("Lipscomb", "D1", "ASUN", "lipscomb.edu", "safety", None, None),
    ("North Alabama", "D1", "ASUN", "una.edu", "safety", None, None),
    ("North Florida", "D1", "ASUN", "unf.edu", "safety", None, None),
    ("Queens (NC)", "D1", "ASUN", "queens.edu", "safety", None, None),
    ("Stetson", "D1", "ASUN", "stetson.edu", "safety", None, None),
    ("West Georgia", "D1", "ASUN", "westga.edu", "safety", None, None),

    # --- Horizon (8) ---
    ("Northern Kentucky", "D1", "Horizon", "nku.edu", "safety", None, None),
    ("Oakland", "D1", "Horizon", "oakland.edu", "safety", None, None),
    ("Purdue Fort Wayne", "D1", "Horizon", "pfw.edu", "safety", None, None),
    ("Wright State", "D1", "Horizon", "wright.edu", "safety", None, None),
    ("Youngstown State", "D1", "Horizon", "ysu.edu", "safety", None, None),
    ("Cleveland State", "D1", "Horizon", "csuohio.edu", "safety", None, None),
    ("Milwaukee", "D1", "Horizon", "uwm.edu", "safety", None, None),
    ("UIC", "D1", "Horizon", "uic.edu", "safety", None, None),

    # --- MAAC (8) ---
    ("Canisius", "D1", "MAAC", "canisius.edu", "safety", None, None),
    ("Fairfield", "D1", "MAAC", "fairfield.edu", "safety", None, None),
    ("Iona", "D1", "MAAC", "iona.edu", "safety", None, None),
    ("Manhattan", "D1", "MAAC", "manhattan.edu", "safety", None, None),
    ("Marist", "D1", "MAAC", "marist.edu", "safety", None, None),
    ("Niagara", "D1", "MAAC", "niagara.edu", "safety", None, None),
    ("Quinnipiac", "D1", "MAAC", "quinnipiac.edu", "safety", None, None),
    ("Rider", "D1", "MAAC", "rider.edu", "safety", None, None),
    ("Saint Peter's", "D1", "MAAC", "saintpeters.edu", "safety", None, None),
    ("Siena", "D1", "MAAC", "siena.edu", "safety", None, None),
    ("Mount St. Mary's", "D1", "MAAC", "msmary.edu", "safety", None, None),

    # --- MAC (10 baseball) ---
    ("Ball State", "D1", "MAC", "bsu.edu", "safety", None, None),
    ("Bowling Green", "D1", "MAC", "bgsu.edu", "safety", None, None),
    ("Central Michigan", "D1", "MAC", "cmich.edu", "safety", None, None),
    ("Eastern Michigan", "D1", "MAC", "emich.edu", "safety", None, None),
    ("Kent State", "D1", "MAC", "kent.edu", "safety", None, None),
    ("Miami (OH)", "D1", "MAC", "miamioh.edu", "safety", None, None),
    ("Northern Illinois", "D1", "MAC", "niu.edu", "safety", None, None),
    ("Ohio", "D1", "MAC", "ohio.edu", "safety", None, None),
    ("Toledo", "D1", "MAC", "utoledo.edu", "safety", None, None),
    ("Western Michigan", "D1", "MAC", "wmich.edu", "safety", None, None),

    # --- NEC (8) ---
    ("Central Connecticut", "D1", "NEC", "ccsu.edu", "safety", None, None),
    ("Fairleigh Dickinson", "D1", "NEC", "fdu.edu", "safety", None, None),
    ("Le Moyne", "D1", "NEC", "lemoyne.edu", "safety", None, None),
    ("LIU", "D1", "NEC", "liu.edu", "safety", None, None),
    ("Mercyhurst", "D1", "NEC", "mercyhurst.edu", "safety", None, None),
    ("Saint Francis (PA)", "D1", "NEC", "francis.edu", "safety", None, None),
    ("Stonehill", "D1", "NEC", "stonehill.edu", "safety", None, None),
    ("Wagner", "D1", "NEC", "wagner.edu", "safety", None, None),

    # --- OVC (9) ---
    ("Eastern Illinois", "D1", "OVC", "eiu.edu", "safety", None, None),
    ("Lindenwood", "D1", "OVC", "lindenwood.edu", "safety", None, None),
    ("Little Rock", "D1", "OVC", "ualr.edu", "safety", None, None),
    ("Morehead State", "D1", "OVC", "moreheadstate.edu", "safety", None, None),
    ("SIU Edwardsville", "D1", "OVC", "siue.edu", "safety", None, None),
    ("Southeast Missouri", "D1", "OVC", "semo.edu", "safety", None, None),
    ("Southern Indiana", "D1", "OVC", "usi.edu", "safety", None, None),
    ("Tennessee Tech", "D1", "OVC", "tntech.edu", "safety", None, None),
    ("UT Martin", "D1", "OVC", "utm.edu", "safety", None, None),
    ("Western Illinois", "D1", "OVC", "wiu.edu", "safety", None, None),

    # --- Patriot (5 baseball) ---
    ("Army", "D1", "Patriot", "westpoint.edu", "safety", None, None),
    ("Bucknell", "D1", "Patriot", "bucknell.edu", "safety", None, None),
    ("Holy Cross", "D1", "Patriot", "holycross.edu", "safety", None, None),
    ("Lafayette", "D1", "Patriot", "lafayette.edu", "safety", None, None),
    ("Lehigh", "D1", "Patriot", "lehigh.edu", "safety", None, None),
    ("Navy", "D1", "Patriot", "usna.edu", "safety", None, None),

    # --- Southland (9) ---
    ("Houston Christian", "D1", "Southland", "hbu.edu", "safety", None, None),
    ("Incarnate Word", "D1", "Southland", "uiwtx.edu", "safety", None, None),
    ("Lamar", "D1", "Southland", "lamar.edu", "safety", None, None),
    ("McNeese", "D1", "Southland", "mcneese.edu", "safety", None, None),
    ("New Orleans", "D1", "Southland", "uno.edu", "safety", None, None),
    ("Nicholls", "D1", "Southland", "nicholls.edu", "safety", None, None),
    ("Northwestern State", "D1", "Southland", "nsula.edu", "safety", None, None),
    ("SE Louisiana", "D1", "Southland", "southeastern.edu", "safety", None, None),
    ("Stephen F. Austin", "D1", "Southland", "sfasu.edu", "safety", None, None),
    ("Texas A&M Corpus Christi", "D1", "Southland", "tamucc.edu", "safety", None, None),

    # --- Southern (11 baseball) ---
    ("Chattanooga", "D1", "SoCon", "utc.edu", "safety", None, None),
    ("The Citadel", "D1", "SoCon", "citadel.edu", "safety", None, None),
    ("East Tennessee State", "D1", "SoCon", "etsu.edu", "safety", None, None),
    ("Furman", "D1", "SoCon", "furman.edu", "safety", None, None),
    ("Mercer", "D1", "SoCon", "mercer.edu", "safety", None, None),
    ("Samford", "D1", "SoCon", "samford.edu", "safety", None, None),
    ("UNC Greensboro", "D1", "SoCon", "uncg.edu", "safety", None, None),
    ("VMI", "D1", "SoCon", "vmi.edu", "safety", None, None),
    ("Western Carolina", "D1", "SoCon", "wcu.edu", "safety", None, None),
    ("Wofford", "D1", "SoCon", "wofford.edu", "safety", None, None),

    # --- SWAC (10 baseball) ---
    ("Alabama A&M", "D1", "SWAC", "aamu.edu", "safety", None, None),
    ("Alabama State", "D1", "SWAC", "alasu.edu", "safety", None, None),
    ("Alcorn State", "D1", "SWAC", "alcorn.edu", "safety", None, None),
    ("Arkansas-Pine Bluff", "D1", "SWAC", "uapb.edu", "safety", None, None),
    ("Bethune-Cookman", "D1", "SWAC", "cookman.edu", "safety", None, None),
    ("Florida A&M", "D1", "SWAC", "famu.edu", "safety", None, None),
    ("Grambling", "D1", "SWAC", "gram.edu", "safety", None, None),
    ("Jackson State", "D1", "SWAC", "jsums.edu", "safety", None, None),
    ("Mississippi Valley State", "D1", "SWAC", "mvsu.edu", "safety", None, None),
    ("Prairie View A&M", "D1", "SWAC", "pvamu.edu", "safety", None, None),
    ("Southern", "D1", "SWAC", "subr.edu", "safety", None, None),
    ("Texas Southern", "D1", "SWAC", "tsu.edu", "safety", None, None),

    # --- MEAC (5 baseball) ---
    ("Coppin State", "D1", "MEAC", "coppin.edu", "safety", None, None),
    ("Delaware State", "D1", "MEAC", "desu.edu", "safety", None, None),
    ("Howard", "D1", "MEAC", "howard.edu", "safety", None, None),
    ("Maryland Eastern Shore", "D1", "MEAC", "umes.edu", "safety", None, None),
    ("Norfolk State", "D1", "MEAC", "nsu.edu", "safety", None, None),
    ("North Carolina Central", "D1", "MEAC", "nccu.edu", "safety", None, None),
    ("South Carolina State", "D1", "MEAC", "scsu.edu", "safety", None, None),

    # --- Summit (8) ---
    ("Kansas City", "D1", "Summit", "umkc.edu", "safety", None, None),
    ("North Dakota State", "D1", "Summit", "ndsu.edu", "safety", None, None),
    ("Omaha", "D1", "Summit", "unomaha.edu", "safety", None, None),
    ("Oral Roberts", "D1", "Summit", "oru.edu", "safety", None, None),
    ("South Dakota State", "D1", "Summit", "sdstate.edu", "safety", None, None),
    ("St. Thomas (MN)", "D1", "Summit", "stthomas.edu", "safety", None, None),
    ("Western Illinois", "D1", "Summit", "wiu.edu", "safety", None, None),

    # --- WAC (8) ---
    ("Abilene Christian", "D1", "WAC", "acu.edu", "safety", None, None),
    ("Cal Baptist", "D1", "WAC", "calbaptist.edu", "safety", None, None),
    ("Grand Canyon", "D1", "WAC", "gcu.edu", "safety", None, None),
    ("Seattle", "D1", "WAC", "seattleu.edu", "safety", None, None),
    ("Southern Utah", "D1", "WAC", "suu.edu", "safety", None, None),
    ("Tarleton", "D1", "WAC", "tarleton.edu", "safety", None, None),
    ("UT Arlington", "D1", "WAC", "uta.edu", "safety", None, None),
    ("Utah Valley", "D1", "WAC", "uvu.edu", "safety", None, None),

    # --- AEC (6 baseball) ---
    ("Albany", "D1", "AEC", "albany.edu", "safety", None, None),
    ("Binghamton", "D1", "AEC", "binghamton.edu", "safety", None, None),
    ("Bryant", "D1", "AEC", "bryant.edu", "safety", None, None),
    ("Maine", "D1", "AEC", "maine.edu", "safety", None, None),
    ("NJIT", "D1", "AEC", "njit.edu", "safety", None, None),
    ("UMass Lowell", "D1", "AEC", "uml.edu", "safety", None, None),

    # --- Ivy (8) ---
    ("Brown", "D1", "Ivy", "brown.edu", "safety", None, None),
    ("Columbia", "D1", "Ivy", "columbia.edu", "safety", None, None),
    ("Cornell", "D1", "Ivy", "cornell.edu", "safety", None, None),
    ("Dartmouth", "D1", "Ivy", "dartmouth.edu", "safety", None, None),
    ("Harvard", "D1", "Ivy", "harvard.edu", "safety", None, None),
    ("Penn", "D1", "Ivy", "upenn.edu", "safety", None, None),
    ("Princeton", "D1", "Ivy", "princeton.edu", "safety", None, None),
    ("Yale", "D1", "Ivy", "yale.edu", "safety", None, None),

    # --- West Coast (10) ---
    ("Gonzaga", "D1", "WCC", "gonzaga.edu", "safety", None, None),
    ("Loyola Marymount", "D1", "WCC", "lmu.edu", "safety", None, None),
    ("Oregon State", "D1", "WCC", "oregonstate.edu", "match", None, None),
    ("Pacific", "D1", "WCC", "pacific.edu", "safety", None, None),
    ("Pepperdine", "D1", "WCC", "pepperdine.edu", "safety", None, None),
    ("Portland", "D1", "WCC", "up.edu", "safety", None, None),
    ("Saint Mary's", "D1", "WCC", "stmarys-ca.edu", "safety", None, None),
    ("San Diego", "D1", "WCC", "sandiego.edu", "safety", None, None),
    ("San Francisco", "D1", "WCC", "usfca.edu", "safety", None, None),
    ("Santa Clara", "D1", "WCC", "scu.edu", "safety", None, None),
    ("Washington State", "D1", "WCC", "wsu.edu", "safety", None, None),

    # =========================================================================
    # NCAA DIVISION II (selected strong programs)
    # =========================================================================
    ("Angelo State", "D2", "Lone Star", "angelo.edu", "safety", None, None),
    ("Augustana (SD)", "D2", "NSIC", "augie.edu", "safety", None, None),
    ("Azusa Pacific", "D2", "PacWest", "apu.edu", "safety", None, None),
    ("Barry", "D2", "SSC", "barry.edu", "safety", None, None),
    ("Bemidji State", "D2", "NSIC", "bemidjistate.edu", "safety", None, None),
    ("Bentley", "D2", "Northeast 10", "bentley.edu", "safety", None, None),
    ("Bloomsburg", "D2", "PSAC", "bloomu.edu", "safety", None, None),
    ("Cal Poly Pomona", "D2", "CCAA", "cpp.edu", "safety", None, None),
    ("Cal State LA", "D2", "CCAA", "calstatela.edu", "safety", None, None),
    ("Cal State Monterey Bay", "D2", "CCAA", "csumb.edu", "safety", None, None),
    ("Cal State San Bernardino", "D2", "CCAA", "csusb.edu", "safety", None, None),
    ("Cal State San Marcos", "D2", "CCAA", "csusm.edu", "safety", None, None),
    ("Cal State Stanislaus", "D2", "CCAA", "csustan.edu", "safety", None, None),
    ("Catawba", "D2", "South Atlantic", "catawba.edu", "safety", None, None),
    ("Central Missouri", "D2", "MIAA", "ucmo.edu", "safety", None, None),
    ("Central Oklahoma", "D2", "MIAA", "uco.edu", "safety", None, None),
    ("Charleston (WV)", "D2", "MEC", "ucwv.edu", "safety", None, None),
    ("Chico State", "D2", "CCAA", "csuchico.edu", "safety", None, None),
    ("Colorado Mesa", "D2", "RMAC", "coloradomesa.edu", "safety", None, None),
    ("Colorado School of Mines", "D2", "RMAC", "mines.edu", "safety", None, None),
    ("Colorado State Pueblo", "D2", "RMAC", "csupueblo.edu", "safety", None, None),
    ("Columbus State", "D2", "Peach Belt", "columbusstate.edu", "safety", None, None),
    ("Concordia (CA)", "D2", "PacWest", "cui.edu", "safety", None, None),
    ("Davenport", "D2", "GLIAC", "davenport.edu", "safety", None, None),
    ("Delta State", "D2", "GSC", "deltastate.edu", "safety", None, None),
    ("East Stroudsburg", "D2", "PSAC", "esu.edu", "safety", None, None),
    ("Eckerd", "D2", "SSC", "eckerd.edu", "safety", None, None),
    ("Embry-Riddle", "D2", "SSC", "erau.edu", "safety", None, None),
    ("Emporia State", "D2", "MIAA", "emporia.edu", "safety", None, None),
    ("Fairmont State", "D2", "MEC", "fairmontstate.edu", "safety", None, None),
    ("Findlay", "D2", "G-MAC", "findlay.edu", "safety", None, None),
    ("Flagler", "D2", "Peach Belt", "flagler.edu", "safety", None, None),
    ("Florida Southern", "D2", "SSC", "flsouthern.edu", "safety", None, None),
    ("Florida Tech", "D2", "SSC", "fit.edu", "safety", None, None),
    ("Franklin Pierce", "D2", "Northeast 10", "franklinpierce.edu", "safety", None, None),
    ("Gannon", "D2", "PSAC", "gannon.edu", "safety", None, None),
    ("Georgia College", "D2", "Peach Belt", "gcsu.edu", "safety", None, None),
    ("Georgia Southwestern", "D2", "Peach Belt", "gsw.edu", "safety", None, None),
    ("Grand Valley State", "D2", "GLIAC", "gvsu.edu", "safety", None, None),
    ("Henderson State", "D2", "GAC", "hsu.edu", "safety", None, None),
    ("Indiana (PA)", "D2", "PSAC", "iup.edu", "safety", None, None),
    ("Lander", "D2", "Peach Belt", "lander.edu", "safety", None, None),
    ("LeMoyne-Owen", "D2", "SIAC", "loc.edu", "safety", None, None),
    ("Lewis", "D2", "GLVC", "lewisu.edu", "safety", None, None),
    ("Lincoln Memorial", "D2", "South Atlantic", "lmunet.edu", "safety", None, None),
    ("Lynn", "D2", "SSC", "lynn.edu", "safety", None, None),
    ("Mars Hill", "D2", "South Atlantic", "mhu.edu", "safety", None, None),
    ("McKendree", "D2", "GLVC", "mckendree.edu", "safety", None, None),
    ("Mercyhurst", "D2", "PSAC", "mercyhurst.edu", "safety", None, None),
    ("Millersville", "D2", "PSAC", "millersville.edu", "safety", None, None),
    ("Minnesota State Mankato", "D2", "NSIC", "mnsu.edu", "safety", None, None),
    ("Minnesota State Moorhead", "D2", "NSIC", "mnstate.edu", "safety", None, None),
    ("Minot State", "D2", "NSIC", "minotstateu.edu", "safety", None, None),
    ("Missouri Southern", "D2", "MIAA", "mssu.edu", "safety", None, None),
    ("Missouri Western", "D2", "MIAA", "missouriwestern.edu", "safety", None, None),
    ("Mount Olive", "D2", "Conf. Carolinas", "umo.edu", "safety", None, None),
    ("Nebraska-Kearney", "D2", "MIAA", "unk.edu", "safety", None, None),
    ("Newberry", "D2", "South Atlantic", "newberry.edu", "safety", None, None),
    ("North Greenville", "D2", "Conf. Carolinas", "ngu.edu", "safety", None, None),
    ("Northwest Missouri", "D2", "MIAA", "nwmissouri.edu", "safety", None, None),
    ("Northwood", "D2", "GMAC", "northwood.edu", "safety", None, None),
    ("Nova Southeastern", "D2", "SSC", "nova.edu", "safety", None, None),
    ("Ouachita Baptist", "D2", "GAC", "obu.edu", "safety", None, None),
    ("Pittsburg State", "D2", "MIAA", "pittstate.edu", "safety", None, None),
    ("Point Loma", "D2", "PacWest", "pointloma.edu", "safety", None, None),
    ("Queens (NC)", "D2", "South Atlantic", "queens.edu", "safety", None, None),
    ("Quincy", "D2", "GLVC", "quincy.edu", "safety", None, None),
    ("Rockhurst", "D2", "GLVC", "rockhurst.edu", "safety", None, None),
    ("Saginaw Valley State", "D2", "GLIAC", "svsu.edu", "safety", None, None),
    ("Saint Anselm", "D2", "Northeast 10", "anselm.edu", "safety", None, None),
    ("Saint Cloud State", "D2", "NSIC", "stcloudstate.edu", "safety", None, None),
    ("Saint Leo", "D2", "SSC", "saintleo.edu", "safety", None, None),
    ("Saint Martin's", "D2", "GNAC", "stmartin.edu", "safety", None, None),
    ("Salem", "D2", "MEC", "salemu.edu", "safety", None, None),
    ("Seton Hill", "D2", "PSAC", "setonhill.edu", "safety", None, None),
    ("Shippensburg", "D2", "PSAC", "ship.edu", "safety", None, None),
    ("Slippery Rock", "D2", "PSAC", "sru.edu", "safety", None, None),
    ("Sonoma State", "D2", "CCAA", "sonoma.edu", "safety", None, None),
    ("South Carolina Aiken", "D2", "Peach Belt", "usca.edu", "safety", None, None),
    ("South Dakota Mines", "D2", "RMAC", "sdsmt.edu", "safety", None, None),
    ("Southeastern Oklahoma", "D2", "GAC", "se.edu", "safety", None, None),
    ("Southern Arkansas", "D2", "GAC", "saumag.edu", "safety", None, None),
    ("Southern Indiana", "D2", "GLVC", "usi.edu", "safety", None, None),
    ("Southwest Baptist", "D2", "GLVC", "sbuniv.edu", "safety", None, None),
    ("Tampa", "D2", "SSC", "ut.edu", "match", None, None),
    ("Tarleton State", "D2", "Lone Star", "tarleton.edu", "safety", None, None),
    ("Texas A&M Commerce", "D2", "Lone Star", "tamuc.edu", "safety", None, None),
    ("Texas A&M Kingsville", "D2", "Lone Star", "tamuk.edu", "safety", None, None),
    ("Truman State", "D2", "GLVC", "truman.edu", "safety", None, None),
    ("UC Colorado Springs", "D2", "RMAC", "uccs.edu", "safety", None, None),
    ("Valdosta State", "D2", "GSC", "valdosta.edu", "safety", None, None),
    ("Walsh", "D2", "G-MAC", "walsh.edu", "safety", None, None),
    ("Washburn", "D2", "MIAA", "washburn.edu", "safety", None, None),
    ("Wayne State (NE)", "D2", "NSIC", "wsc.edu", "safety", None, None),
    ("West Chester", "D2", "PSAC", "wcupa.edu", "safety", None, None),
    ("West Florida", "D2", "GSC", "uwf.edu", "safety", None, None),
    ("West Liberty", "D2", "MEC", "westliberty.edu", "safety", None, None),
    ("West Texas A&M", "D2", "Lone Star", "wtamu.edu", "safety", None, None),
    ("West Virginia State", "D2", "MEC", "wvstateu.edu", "safety", None, None),
    ("Western Colorado", "D2", "RMAC", "western.edu", "safety", None, None),
    ("Wingate", "D2", "South Atlantic", "wingate.edu", "safety", None, None),
    ("Winona State", "D2", "NSIC", "winona.edu", "safety", None, None),

    # =========================================================================
    # NCAA DIVISION III (selected strong programs across regions)
    # =========================================================================
    ("Adrian", "D3", "MIAA", "adrian.edu", "safety", None, None),
    ("Allegheny", "D3", "PAC", "allegheny.edu", "safety", None, None),
    ("Amherst", "D3", "NESCAC", "amherst.edu", "safety", None, None),
    ("Babson", "D3", "NEWMAC", "babson.edu", "safety", None, None),
    ("Baldwin Wallace", "D3", "OAC", "bw.edu", "safety", None, None),
    ("Bates", "D3", "NESCAC", "bates.edu", "safety", None, None),
    ("Birmingham-Southern", "D3", "SAA", "bsc.edu", "safety", None, None),
    ("Bowdoin", "D3", "NESCAC", "bowdoin.edu", "safety", None, None),
    ("Brandeis", "D3", "UAA", "brandeis.edu", "safety", None, None),
    ("Bridgewater (VA)", "D3", "ODAC", "bridgewater.edu", "safety", None, None),
    ("Bridgewater State", "D3", "MASCAC", "bridgew.edu", "safety", None, None),
    ("Brockport", "D3", "SUNYAC", "brockport.edu", "safety", None, None),
    ("Buena Vista", "D3", "ARC", "bvu.edu", "safety", None, None),
    ("CalTech", "D3", "SCIAC", "caltech.edu", "safety", None, None),
    ("Carleton", "D3", "MIAC", "carleton.edu", "safety", None, None),
    ("Carnegie Mellon", "D3", "UAA", "andrew.cmu.edu", "safety", None, None),
    ("Carthage", "D3", "CCIW", "carthage.edu", "safety", None, None),
    ("Case Western Reserve", "D3", "UAA", "case.edu", "safety", None, None),
    ("Catholic", "D3", "Landmark", "cua.edu", "safety", None, None),
    ("Chapman", "D3", "SCIAC", "chapman.edu", "safety", None, None),
    ("Christopher Newport", "D3", "Coast-to-Coast", "cnu.edu", "safety", None, None),
    ("Claremont-Mudd-Scripps", "D3", "SCIAC", "cmc.edu", "safety", None, None),
    ("Clarkson", "D3", "Liberty", "clarkson.edu", "safety", None, None),
    ("Coe", "D3", "ARC", "coe.edu", "safety", None, None),
    ("Colby", "D3", "NESCAC", "colby.edu", "safety", None, None),
    ("Concordia (WI)", "D3", "NACC", "cuw.edu", "safety", None, None),
    ("Connecticut College", "D3", "NESCAC", "conncoll.edu", "safety", None, None),
    ("Cortland", "D3", "SUNYAC", "cortland.edu", "safety", None, None),
    ("Curry", "D3", "Commonwealth Coast", "curry.edu", "safety", None, None),
    ("Denison", "D3", "NCAC", "denison.edu", "safety", None, None),
    ("DePauw", "D3", "NCAC", "depauw.edu", "safety", None, None),
    ("Dickinson", "D3", "Centennial", "dickinson.edu", "safety", None, None),
    ("Eastern Connecticut", "D3", "Little East", "easternct.edu", "safety", None, None),
    ("Elmhurst", "D3", "CCIW", "elmhurst.edu", "safety", None, None),
    ("Emory", "D3", "UAA", "emory.edu", "safety", None, None),
    ("Endicott", "D3", "Commonwealth Coast", "endicott.edu", "safety", None, None),
    ("Fontbonne", "D3", "SLIAC", "fontbonne.edu", "safety", None, None),
    ("Franklin & Marshall", "D3", "Centennial", "fandm.edu", "safety", None, None),
    ("Frostburg State", "D3", "MAC", "frostburg.edu", "safety", None, None),
    ("Gettysburg", "D3", "Centennial", "gettysburg.edu", "safety", None, None),
    ("Gordon", "D3", "Commonwealth Coast", "gordon.edu", "safety", None, None),
    ("Goucher", "D3", "Landmark", "goucher.edu", "safety", None, None),
    ("Grove City", "D3", "Presidents'", "gcc.edu", "safety", None, None),
    ("Hamilton", "D3", "NESCAC", "hamilton.edu", "safety", None, None),
    ("Hampden-Sydney", "D3", "ODAC", "hsc.edu", "safety", None, None),
    ("Hanover", "D3", "HCAC", "hanover.edu", "safety", None, None),
    ("Hartwick", "D3", "Empire 8", "hartwick.edu", "safety", None, None),
    ("Haverford", "D3", "Centennial", "haverford.edu", "safety", None, None),
    ("Hope", "D3", "MIAA", "hope.edu", "safety", None, None),
    ("Illinois Wesleyan", "D3", "CCIW", "iwu.edu", "safety", None, None),
    ("Ithaca", "D3", "Liberty", "ithaca.edu", "safety", None, None),
    ("Johns Hopkins", "D3", "Centennial", "jhu.edu", "safety", None, None),
    ("Juniata", "D3", "Landmark", "juniata.edu", "safety", None, None),
    ("Keene State", "D3", "Little East", "keene.edu", "safety", None, None),
    ("Kenyon", "D3", "NCAC", "kenyon.edu", "safety", None, None),
    ("La Verne", "D3", "SCIAC", "laverne.edu", "safety", None, None),
    ("Lakeland", "D3", "NACC", "lakeland.edu", "safety", None, None),
    ("Linfield", "D3", "Northwest", "linfield.edu", "safety", None, None),
    ("Lycoming", "D3", "MAC", "lycoming.edu", "safety", None, None),
    ("Macalester", "D3", "MIAC", "macalester.edu", "safety", None, None),
    ("Manchester", "D3", "HCAC", "manchester.edu", "safety", None, None),
    ("Marietta", "D3", "OAC", "marietta.edu", "safety", None, None),
    ("MIT", "D3", "NEWMAC", "mit.edu", "safety", None, None),
    ("Middlebury", "D3", "NESCAC", "middlebury.edu", "safety", None, None),
    ("Misericordia", "D3", "MAC", "misericordia.edu", "safety", None, None),
    ("Montclair State", "D3", "NJAC", "montclair.edu", "safety", None, None),
    ("Moravian", "D3", "Landmark", "moravian.edu", "safety", None, None),
    ("Mount Union", "D3", "OAC", "mountunion.edu", "safety", None, None),
    ("Muhlenberg", "D3", "Centennial", "muhlenberg.edu", "safety", None, None),
    ("Nazareth", "D3", "Empire 8", "naz.edu", "safety", None, None),
    ("Neumann", "D3", "Atlantic East", "neumann.edu", "safety", None, None),
    ("New York University", "D3", "UAA", "nyu.edu", "safety", None, None),
    ("North Central (IL)", "D3", "CCIW", "noctrl.edu", "safety", None, None),
    ("Oberlin", "D3", "NCAC", "oberlin.edu", "safety", None, None),
    ("Occidental", "D3", "SCIAC", "oxy.edu", "safety", None, None),
    ("Ohio Wesleyan", "D3", "NCAC", "owu.edu", "safety", None, None),
    ("Otterbein", "D3", "OAC", "otterbein.edu", "safety", None, None),
    ("Pomona-Pitzer", "D3", "SCIAC", "pomona.edu", "safety", None, None),
    ("Ramapo", "D3", "NJAC", "ramapo.edu", "safety", None, None),
    ("Randolph-Macon", "D3", "ODAC", "rmc.edu", "safety", None, None),
    ("Redlands", "D3", "SCIAC", "redlands.edu", "safety", None, None),
    ("Rhode Island College", "D3", "Little East", "ric.edu", "safety", None, None),
    ("Rhodes", "D3", "SAA", "rhodes.edu", "safety", None, None),
    ("Roanoke", "D3", "ODAC", "roanoke.edu", "safety", None, None),
    ("Rochester", "D3", "Liberty", "rochester.edu", "safety", None, None),
    ("Roger Williams", "D3", "Commonwealth Coast", "rwu.edu", "safety", None, None),
    ("Rose-Hulman", "D3", "HCAC", "rose-hulman.edu", "safety", None, None),
    ("Rowan", "D3", "NJAC", "rowan.edu", "safety", None, None),
    ("RPI", "D3", "Liberty", "rpi.edu", "safety", None, None),
    ("Salisbury", "D3", "Coast-to-Coast", "salisbury.edu", "safety", None, None),
    ("Salve Regina", "D3", "Commonwealth Coast", "salve.edu", "safety", None, None),
    ("Skidmore", "D3", "Liberty", "skidmore.edu", "safety", None, None),
    ("Southwestern", "D3", "SCAC", "southwestern.edu", "safety", None, None),
    ("Springfield", "D3", "NEWMAC", "springfield.edu", "safety", None, None),
    ("St. John Fisher", "D3", "Empire 8", "sjfc.edu", "safety", None, None),
    ("St. Lawrence", "D3", "Liberty", "stlawu.edu", "safety", None, None),
    ("St. Mary's (MD)", "D3", "Coast-to-Coast", "smcm.edu", "safety", None, None),
    ("St. Norbert", "D3", "NACC", "snc.edu", "safety", None, None),
    ("St. Olaf", "D3", "MIAC", "stolaf.edu", "safety", None, None),
    ("St. Scholastica", "D3", "MIAC", "css.edu", "safety", None, None),
    ("St. Thomas (MN)", "D3", "MIAC", "stthomas.edu", "safety", None, None),
    ("Stevens", "D3", "MAC", "stevens.edu", "safety", None, None),
    ("Stockton", "D3", "NJAC", "stockton.edu", "safety", None, None),
    ("SUNY Geneseo", "D3", "SUNYAC", "geneseo.edu", "safety", None, None),
    ("SUNY New Paltz", "D3", "SUNYAC", "newpaltz.edu", "safety", None, None),
    ("SUNY Oneonta", "D3", "SUNYAC", "oneonta.edu", "safety", None, None),
    ("Susquehanna", "D3", "Landmark", "susqu.edu", "safety", None, None),
    ("Swarthmore", "D3", "Centennial", "swarthmore.edu", "safety", None, None),
    ("Texas Lutheran", "D3", "ASC", "tlu.edu", "safety", None, None),
    ("Trine", "D3", "MIAA", "trine.edu", "safety", None, None),
    ("Trinity (CT)", "D3", "NESCAC", "trincoll.edu", "safety", None, None),
    ("Trinity (TX)", "D3", "SCAC", "trinity.edu", "safety", None, None),
    ("Tufts", "D3", "NESCAC", "tufts.edu", "safety", None, None),
    ("Ursinus", "D3", "Centennial", "ursinus.edu", "safety", None, None),
    ("Utica", "D3", "Empire 8", "utica.edu", "safety", None, None),
    ("Vassar", "D3", "Liberty", "vassar.edu", "safety", None, None),
    ("Wabash", "D3", "NCAC", "wabash.edu", "safety", None, None),
    ("Wartburg", "D3", "ARC", "wartburg.edu", "safety", None, None),
    ("Washington & Jefferson", "D3", "PAC", "washjeff.edu", "safety", None, None),
    ("Washington & Lee", "D3", "ODAC", "wlu.edu", "safety", None, None),
    ("Washington (MO)", "D3", "UAA", "wustl.edu", "safety", None, None),
    ("Wesleyan", "D3", "NESCAC", "wesleyan.edu", "safety", None, None),
    ("Western New England", "D3", "Commonwealth Coast", "wne.edu", "safety", None, None),
    ("Westfield State", "D3", "MASCAC", "westfield.ma.edu", "safety", None, None),
    ("Wheaton (IL)", "D3", "CCIW", "wheaton.edu", "safety", None, None),
    ("Wheaton (MA)", "D3", "NEWMAC", "wheatoncollege.edu", "safety", None, None),
    ("Whitman", "D3", "Northwest", "whitman.edu", "safety", None, None),
    ("Whittier", "D3", "SCIAC", "whittier.edu", "safety", None, None),
    ("Whitworth", "D3", "Northwest", "whitworth.edu", "safety", None, None),
    ("Widener", "D3", "MAC", "widener.edu", "safety", None, None),
    ("Wilkes", "D3", "MAC", "wilkes.edu", "safety", None, None),
    ("Williams", "D3", "NESCAC", "williams.edu", "safety", None, None),
    ("Wisconsin-La Crosse", "D3", "WIAC", "uwlax.edu", "safety", None, None),
    ("Wisconsin-Oshkosh", "D3", "WIAC", "uwosh.edu", "safety", None, None),
    ("Wisconsin-Platteville", "D3", "WIAC", "uwplatt.edu", "safety", None, None),
    ("Wisconsin-Stevens Point", "D3", "WIAC", "uwsp.edu", "safety", None, None),
    ("Wisconsin-Stout", "D3", "WIAC", "uwstout.edu", "safety", None, None),
    ("Wisconsin-Whitewater", "D3", "WIAC", "uww.edu", "safety", None, None),
    ("Wooster", "D3", "NCAC", "wooster.edu", "safety", None, None),
    ("Worcester State", "D3", "MASCAC", "worcester.edu", "safety", None, None),
    ("WPI", "D3", "NEWMAC", "wpi.edu", "safety", None, None),
    ("York (PA)", "D3", "MAC", "ycp.edu", "safety", None, None),

    # =========================================================================
    # NAIA (selected strong programs)
    # =========================================================================
    ("Antelope Valley", "NAIA", "Cal Pac", "avc.edu", "safety", None, None),
    ("Arizona Christian", "NAIA", "Sooner", "arizonachristian.edu", "safety", None, None),
    ("Asbury", "NAIA", "AAC", "asbury.edu", "safety", None, None),
    ("Auburn Montgomery", "NAIA", "Southern States", "aum.edu", "safety", None, None),
    ("Avila", "NAIA", "Heart of America", "avila.edu", "safety", None, None),
    ("Baker", "NAIA", "Heart of America", "bakeru.edu", "safety", None, None),
    ("Bellevue", "NAIA", "North Star", "bellevue.edu", "safety", None, None),
    ("Bethel (IN)", "NAIA", "Crossroads", "bethelcollege.edu", "safety", None, None),
    ("Bethel (KS)", "NAIA", "KCAC", "bethelks.edu", "safety", None, None),
    ("Bethel (TN)", "NAIA", "Mid-South", "bethelu.edu", "safety", None, None),
    ("Brescia", "NAIA", "Mid-South", "brescia.edu", "safety", None, None),
    ("Briar Cliff", "NAIA", "GPAC", "briarcliff.edu", "safety", None, None),
    ("Bryan", "NAIA", "AAC", "bryan.edu", "safety", None, None),
    ("Campbellsville", "NAIA", "Mid-South", "campbellsville.edu", "safety", None, None),
    ("Carroll (MT)", "NAIA", "Frontier", "carroll.edu", "safety", None, None),
    ("College of Idaho", "NAIA", "Cascade", "collegeofidaho.edu", "safety", None, None),
    ("Concordia (NE)", "NAIA", "GPAC", "cune.edu", "safety", None, None),
    ("Cumberland (TN)", "NAIA", "Mid-South", "cumberland.edu", "safety", None, None),
    ("Cumberlands", "NAIA", "Mid-South", "ucumberlands.edu", "safety", None, None),
    ("Dakota State", "NAIA", "NSAA", "dsu.edu", "safety", None, None),
    ("Dakota Wesleyan", "NAIA", "GPAC", "dwu.edu", "safety", None, None),
    ("Doane", "NAIA", "GPAC", "doane.edu", "safety", None, None),
    ("Dordt", "NAIA", "GPAC", "dordt.edu", "safety", None, None),
    ("East Texas Baptist", "NAIA", "ASC", "etbu.edu", "safety", None, None),
    ("Faulkner", "NAIA", "Southern States", "faulkner.edu", "safety", None, None),
    ("Florida Memorial", "NAIA", "Sun", "fmuniv.edu", "safety", None, None),
    ("Friends", "NAIA", "KCAC", "friends.edu", "safety", None, None),
    ("Georgetown (KY)", "NAIA", "Mid-South", "georgetowncollege.edu", "safety", None, None),
    ("Grand View", "NAIA", "Heart of America", "grandview.edu", "safety", None, None),
    ("Hannibal-LaGrange", "NAIA", "AMC", "hlg.edu", "safety", None, None),
    ("Hastings", "NAIA", "GPAC", "hastings.edu", "safety", None, None),
    ("Hope International", "NAIA", "GSAC", "hiu.edu", "safety", None, None),
    ("Huntington", "NAIA", "Crossroads", "huntington.edu", "safety", None, None),
    ("Indiana Tech", "NAIA", "WHAC", "indianatech.edu", "safety", None, None),
    ("Indiana Wesleyan", "NAIA", "Crossroads", "indwes.edu", "safety", None, None),
    ("Iowa Wesleyan", "NAIA", "Heart of America", "iw.edu", "safety", None, None),
    ("Jamestown", "NAIA", "NSAA", "uj.edu", "safety", None, None),
    ("Kansas Wesleyan", "NAIA", "KCAC", "kwu.edu", "safety", None, None),
    ("Keiser", "NAIA", "Sun", "keiseruniversity.edu", "safety", None, None),
    ("Lewis-Clark State", "NAIA", "Cascade", "lcsc.edu", "match", None, None),  # Strong NAIA program
    ("Life", "NAIA", "Mid-South", "life.edu", "safety", None, None),
    ("Lindenwood (Belleville)", "NAIA", "AMC", "lindenwood.edu", "safety", None, None),
    ("Lindsey Wilson", "NAIA", "Mid-South", "lindsey.edu", "safety", None, None),
    ("Loyola (LA)", "NAIA", "Southern States", "loyno.edu", "safety", None, None),
    ("Lyon", "NAIA", "AMC", "lyon.edu", "safety", None, None),
    ("Marian (IN)", "NAIA", "Crossroads", "marian.edu", "safety", None, None),
    ("Mayville State", "NAIA", "NSAA", "mayvillestate.edu", "safety", None, None),
    ("McPherson", "NAIA", "KCAC", "mcpherson.edu", "safety", None, None),
    ("Menlo", "NAIA", "Cal Pac", "menlo.edu", "safety", None, None),
    ("MidAmerica Nazarene", "NAIA", "Heart of America", "mnu.edu", "safety", None, None),
    ("Midland", "NAIA", "GPAC", "midlandu.edu", "safety", None, None),
    ("Midway", "NAIA", "Mid-South", "midway.edu", "safety", None, None),
    ("Milligan", "NAIA", "AAC", "milligan.edu", "safety", None, None),
    ("Missouri Baptist", "NAIA", "AMC", "mobap.edu", "safety", None, None),
    ("Missouri Valley", "NAIA", "Heart of America", "moval.edu", "safety", None, None),
    ("Mount Marty", "NAIA", "GPAC", "mountmarty.edu", "safety", None, None),
    ("Mount Mercy", "NAIA", "Heart of America", "mtmercy.edu", "safety", None, None),
    ("Mount Vernon Nazarene", "NAIA", "Crossroads", "mvnu.edu", "safety", None, None),
    ("Northwestern (IA)", "NAIA", "GPAC", "nwciowa.edu", "safety", None, None),
    ("Oklahoma Baptist", "NAIA", "Sooner", "okbu.edu", "safety", None, None),
    ("Oklahoma City", "NAIA", "Sooner", "okcu.edu", "match", None, None),  # Strong NAIA program
    ("Oklahoma Panhandle", "NAIA", "Sooner", "opsu.edu", "safety", None, None),
    ("Oklahoma Wesleyan", "NAIA", "KCAC", "okwu.edu", "safety", None, None),
    ("Olivet Nazarene", "NAIA", "Crossroads", "olivet.edu", "safety", None, None),
    ("Ottawa (KS)", "NAIA", "KCAC", "ottawa.edu", "safety", None, None),
    ("Park", "NAIA", "Heart of America", "park.edu", "safety", None, None),
    ("Peru State", "NAIA", "Heart of America", "peru.edu", "safety", None, None),
    ("Point", "NAIA", "AAC", "point.edu", "safety", None, None),
    ("Point Park", "NAIA", "RSC", "pointpark.edu", "safety", None, None),
    ("Reinhardt", "NAIA", "AAC", "reinhardt.edu", "safety", None, None),
    ("Saint Ambrose", "NAIA", "Chicagoland", "sau.edu", "safety", None, None),
    ("Saint Francis (IL)", "NAIA", "Chicagoland", "stfrancis.edu", "safety", None, None),
    ("Saint Thomas (FL)", "NAIA", "Sun", "stu.edu", "safety", None, None),
    ("Saint Xavier", "NAIA", "Chicagoland", "sxu.edu", "safety", None, None),
    ("Science & Arts", "NAIA", "Sooner", "usao.edu", "safety", None, None),
    ("Shawnee State", "NAIA", "Mid-South", "shawnee.edu", "safety", None, None),
    ("Siena Heights", "NAIA", "WHAC", "sienaheights.edu", "safety", None, None),
    ("Sioux Falls", "NAIA", "NSIC", "usiouxfalls.edu", "safety", None, None),
    ("Southeastern (FL)", "NAIA", "Sun", "seu.edu", "safety", None, None),
    ("Southwestern Christian", "NAIA", "Sooner", "swcu.edu", "safety", None, None),
    ("Spring Arbor", "NAIA", "Crossroads", "arbor.edu", "safety", None, None),
    ("Sterling", "NAIA", "KCAC", "sterling.edu", "safety", None, None),
    ("Tabor", "NAIA", "KCAC", "tabor.edu", "safety", None, None),
    ("Tennessee Wesleyan", "NAIA", "AAC", "tnwesleyan.edu", "safety", None, None),
    ("Texas Wesleyan", "NAIA", "Sooner", "txwes.edu", "safety", None, None),
    ("Truett-McConnell", "NAIA", "AAC", "truett.edu", "safety", None, None),
    ("Union (KY)", "NAIA", "AAC", "unionky.edu", "safety", None, None),
    ("Union (TN)", "NAIA", "AAC", "uu.edu", "safety", None, None),
    ("Valley City State", "NAIA", "NSAA", "vcsu.edu", "safety", None, None),
    ("Vanguard", "NAIA", "GSAC", "vanguard.edu", "safety", None, None),
    ("Viterbo", "NAIA", "NSAA", "viterbo.edu", "safety", None, None),
    ("Wayland Baptist", "NAIA", "Sooner", "wbu.edu", "safety", None, None),
    ("Webber International", "NAIA", "Sun", "webber.edu", "safety", None, None),
    ("Westmont", "NAIA", "GSAC", "westmont.edu", "safety", None, None),
    ("William Carey", "NAIA", "Southern States", "wmcarey.edu", "safety", None, None),
    ("William Jessup", "NAIA", "Cal Pac", "jessup.edu", "safety", None, None),
    ("William Jewell", "NAIA", "GLVC", "jewell.edu", "safety", None, None),
    ("William Penn", "NAIA", "Heart of America", "wmpenn.edu", "safety", None, None),
    ("Williams Baptist", "NAIA", "AMC", "williamsbaptistcollege.com", "safety", None, None),
    ("Xavier (LA)", "NAIA", "Gulf Coast", "xula.edu", "safety", None, None),
    ("York (NE)", "NAIA", "KCAC", "york.edu", "safety", None, None),

    # =========================================================================
    # NJCAA (selected key JUCO programs)
    # =========================================================================
    ("Blinn College", "JUCO", "NJCAA D1", "blinn.edu", "safety", None, None),
    ("Cabrillo College", "JUCO", "CCCAA", "cabrillo.edu", "safety", None, None),
    ("Central Arizona", "JUCO", "ACCAC", "centralaz.edu", "safety", None, None),
    ("Chipola College", "JUCO", "NJCAA D1", "chipola.edu", "safety", None, None),
    ("Cisco College", "JUCO", "NTJCAC", "cisco.edu", "safety", None, None),
    ("Cochise College", "JUCO", "ACCAC", "cochise.edu", "safety", None, None),
    ("College of Central Florida", "JUCO", "NJCAA D1", "cf.edu", "safety", None, None),
    ("College of Southern Idaho", "JUCO", "SWAC", "csi.edu", "safety", None, None),
    ("College of Southern Nevada", "JUCO", "Scenic West", "csn.edu", "safety", None, None),
    ("Cowley College", "JUCO", "KJCCC", "cowley.edu", "safety", None, None),
    ("Crowder College", "JUCO", "Region 16", "crowder.edu", "safety", None, None),
    ("Cypress College", "JUCO", "CCCAA", "cypresscollege.edu", "safety", None, None),
    ("Eastern Oklahoma State", "JUCO", "NJCAA D2", "eosc.edu", "safety", None, None),
    ("Florence-Darlington Tech", "JUCO", "NJCAA D2", "fdtc.edu", "safety", None, None),
    ("Galveston College", "JUCO", "NTJCAC", "gc.edu", "safety", None, None),
    ("Garden City CC", "JUCO", "KJCCC", "gcccks.edu", "safety", None, None),
    ("Gateway CC", "JUCO", "NJCAA D1", "gatewaycc.edu", "safety", None, None),
    ("Grayson College", "JUCO", "NTJCAC", "grayson.edu", "safety", None, None),
    ("Hill College", "JUCO", "NTJCAC", "hillcollege.edu", "safety", None, None),
    ("Hillsborough CC", "JUCO", "FCSAA", "hccfl.edu", "safety", None, None),
    ("Hutchinson CC", "JUCO", "KJCCC", "hutchcc.edu", "safety", None, None),
    ("Indian Hills CC", "JUCO", "Region 11", "indianhills.edu", "safety", None, None),
    ("Indian River State", "JUCO", "FCSAA", "irsc.edu", "safety", None, None),
    ("Iowa Central CC", "JUCO", "Region 11", "iowacentral.edu", "safety", None, None),
    ("Iowa Western CC", "JUCO", "Region 11", "iwcc.edu", "safety", None, None),
    ("Jefferson College", "JUCO", "Region 16", "jeffco.edu", "safety", None, None),
    ("John A. Logan College", "JUCO", "GRAC", "jalc.edu", "safety", None, None),
    ("Johnson County CC", "JUCO", "KJCCC", "jccc.edu", "safety", None, None),
    ("Kankakee CC", "JUCO", "GRAC", "kcc.edu", "safety", None, None),
    ("Kaskaskia College", "JUCO", "GRAC", "kaskaskia.edu", "safety", None, None),
    ("Kirkwood CC", "JUCO", "Region 11", "kirkwood.edu", "safety", None, None),
    ("Lackawanna College", "JUCO", "NJCAA D2", "lackawanna.edu", "safety", None, None),
    ("Lake Land College", "JUCO", "GRAC", "lakeland.cc.il.us", "safety", None, None),
    ("Lamar CC", "JUCO", "Empire", "lamarcc.edu", "safety", None, None),
    ("Lassen CC", "JUCO", "CCCAA", "lassencollege.edu", "safety", None, None),
    ("LSU Eunice", "JUCO", "NJCAA D2", "lsue.edu", "safety", None, None),
    ("Madison Area Tech", "JUCO", "N4C", "madisoncollege.edu", "safety", None, None),
    ("Manatee-Sarasota State", "JUCO", "FCSAA", "scf.edu", "safety", None, None),
    ("McLennan CC", "JUCO", "NTJCAC", "mclennan.edu", "safety", None, None),
    ("Meridian CC", "JUCO", "MACJC", "meridiancc.edu", "safety", None, None),
    ("Miami Dade College", "JUCO", "FCSAA", "mdc.edu", "safety", None, None),
    ("Mineral Area College", "JUCO", "Region 16", "mineralarea.edu", "safety", None, None),
    ("Mississippi Gulf Coast", "JUCO", "MACJC", "mgccc.edu", "safety", None, None),
    ("Monroe College", "JUCO", "NJCAA D1", "monroecollege.edu", "safety", None, None),
    ("Mt. San Antonio", "JUCO", "CCCAA", "mtsac.edu", "safety", None, None),
    ("Navarro College", "JUCO", "NTJCAC", "navarrocollege.edu", "safety", None, None),
    ("Neosho County CC", "JUCO", "KJCCC", "neosho.edu", "safety", None, None),
    ("New Mexico JC", "JUCO", "WJCAC", "nmjc.edu", "safety", None, None),
    ("North Central Texas", "JUCO", "NTJCAC", "nctc.edu", "safety", None, None),
    ("North Iowa Area CC", "JUCO", "Region 11", "niacc.edu", "safety", None, None),
    ("Northeast CC", "JUCO", "Region 11", "northeast.edu", "safety", None, None),
    ("Northeast Oklahoma A&M", "JUCO", "NJCAA D2", "neo.edu", "safety", None, None),
    ("Northeast Texas CC", "JUCO", "NTJCAC", "ntcc.edu", "safety", None, None),
    ("Northwest Florida State", "JUCO", "FCSAA", "nwfsc.edu", "safety", None, None),
    ("Northwest Mississippi CC", "JUCO", "MACJC", "northwestms.edu", "safety", None, None),
    ("Odessa College", "JUCO", "WJCAC", "odessa.edu", "safety", None, None),
    ("Orange Coast", "JUCO", "CCCAA", "orangecoastcollege.edu", "safety", None, None),
    ("Palm Beach State", "JUCO", "FCSAA", "palmbeachstate.edu", "safety", None, None),
    ("Panola College", "JUCO", "NTJCAC", "panola.edu", "safety", None, None),
    ("Paris JC", "JUCO", "NTJCAC", "parisjc.edu", "safety", None, None),
    ("Parkland College", "JUCO", "GRAC", "parkland.edu", "safety", None, None),
    ("Pasco-Hernando State", "JUCO", "FCSAA", "phsc.edu", "safety", None, None),
    ("Pearl River CC", "JUCO", "MACJC", "prcc.edu", "safety", None, None),
    ("Phoenix College", "JUCO", "ACCAC", "phoenixcollege.edu", "safety", None, None),
    ("Pima CC", "JUCO", "ACCAC", "pima.edu", "safety", None, None),
    ("Polk State", "JUCO", "FCSAA", "polk.edu", "safety", None, None),
    ("Pratt CC", "JUCO", "KJCCC", "prattcc.edu", "safety", None, None),
    ("Rose State", "JUCO", "NJCAA D2", "rose.edu", "safety", None, None),
    ("Saddleback College", "JUCO", "CCCAA", "saddleback.edu", "safety", None, None),
    ("San Jacinto College", "JUCO", "NJCAA D1", "sjcd.edu", "match", None, None),  # Major JUCO baseball
    ("Santa Fe College", "JUCO", "FCSAA", "sfcollege.edu", "safety", None, None),
    ("Seminole State (FL)", "JUCO", "FCSAA", "seminolestate.edu", "safety", None, None),
    ("Seminole State (OK)", "JUCO", "NJCAA D1", "sscok.edu", "safety", None, None),
    ("Shasta College", "JUCO", "CCCAA", "shastacollege.edu", "safety", None, None),
    ("Shelton State CC", "JUCO", "ACCC", "sheltonstate.edu", "safety", None, None),
    ("Sierra College", "JUCO", "CCCAA", "sierracollege.edu", "safety", None, None),
    ("Snead State CC", "JUCO", "ACCC", "snead.edu", "safety", None, None),
    ("South Mountain CC", "JUCO", "ACCAC", "southmountaincc.edu", "safety", None, None),
    ("South Plains College", "JUCO", "WJCAC", "southplainscollege.edu", "safety", None, None),
    ("South Suburban", "JUCO", "GRAC", "ssc.edu", "safety", None, None),
    ("Southeastern CC", "JUCO", "Region 11", "scciowa.edu", "safety", None, None),
    ("Southwestern Illinois", "JUCO", "GRAC", "swic.edu", "safety", None, None),
    ("State College of FL", "JUCO", "FCSAA", "scf.edu", "safety", None, None),
    ("Tallahassee CC", "JUCO", "FCSAA", "tcc.fl.edu", "safety", None, None),
    ("Trinidad State JC", "JUCO", "Empire", "trinidadstate.edu", "safety", None, None),
    ("Tyler JC", "JUCO", "NTJCAC", "tjc.edu", "safety", None, None),
    ("Wabash Valley", "JUCO", "GRAC", "iecc.edu", "safety", None, None),
    ("Wallace State", "JUCO", "ACCC", "wallacestate.edu", "safety", None, None),
    ("Walters State CC", "JUCO", "TCCAA", "ws.edu", "safety", None, None),
    ("Weatherford College", "JUCO", "NTJCAC", "wc.edu", "safety", None, None),
    ("Western Nebraska CC", "JUCO", "Empire", "wncc.edu", "safety", None, None),
    ("Western Oklahoma State", "JUCO", "WJCAC", "wosc.edu", "safety", None, None),
    ("Western Texas College", "JUCO", "WJCAC", "wtc.edu", "safety", None, None),
    ("Yavapai College", "JUCO", "ACCAC", "yavapai.edu", "safety", None, None),
]


def build():
    records = []
    seen = set()
    for entry in SCHOOLS:
        name, div, conf, domain, tier, coach, local = entry
        slug_base = name.lower().replace(" ", "-").replace("(", "").replace(")", "").replace(".", "").replace("&", "and").replace("'", "").replace(",", "")
        slug = f"bb-{slug_base}"
        # Dedupe (some schools appear in multiple lists)
        if slug in seen:
            continue
        seen.add(slug)
        local = local or "baseball"
        records.append({
            "id": slug,
            "name": coach or "",
            "title": "Head Coach",
            "sport": "baseball",
            "school": name,
            "division": div,
            "conference": conf,
            "tier": tier,
            "email_domain": domain,
            "email": f"{local}@{domain}",
            "email_confidence": "program_inbox",
        })
    return records


if __name__ == "__main__":
    records = build()
    out_dir = Path("/home/claude/recruitiq/data")
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "baseball_raw_expanded.json").write_text(json.dumps(records, indent=2))
    print(f"Built {len(records)} baseball school records")
    by_div = {}
    for r in records:
        by_div[r["division"]] = by_div.get(r["division"], 0) + 1
    print("By division:", by_div)
    with_names = sum(1 for r in records if r["name"])
    print(f"With pre-filled coach names: {with_names}")
    print(f"To be lazy-verified on click: {len(records) - with_names}")
